apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-ms
  template:
    metadata:
      labels:
        app: ad-ms
    spec:
      containers:
        - image: rsolinux/ad-ms:latest
          name: ad-ms
          resources:
            requests:
              cpu: "100m"
          env:
            - name: SPRING_APPLICATION_ENVIRONMENTTYPE
              value: "prod"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://suleiman.db.elephantsql.com:5432/obugcdwa
            - name: SPRING_DATASOURCE_USERNAME
              value: obugcdwa
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ad-pg-pass
                  key: password
            - name: SPRING_APPLICATION_NSFWDETECTION
              value: "true"
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/ads/health
              port: server
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /v1/ads/health/readiness
              port: server
            initialDelaySeconds: 30
            periodSeconds: 3
            failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: ad-ms
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: ad-ms
